# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timechangergui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 650)
        MainWindow.setWindowTitle("File Date Changer")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 4)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 1, 0, 2, 3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 3, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearButton.setObjectName("clearButton")
        self.gridLayout_2.addWidget(self.clearButton, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 4)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_2.addWidget(self.textBrowser_2, 4, 0, 1, 4)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 5, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 2, 1, 2)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout_2.addWidget(self.dateTimeEdit, 6, 0, 1, 2)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit_2.setFont(font)
        self.dateTimeEdit_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 6, 2, 1, 2)
        self.applyButton_1 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.applyButton_1.setFont(font)
        self.applyButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.applyButton_1.setObjectName("applyButton_1")
        self.gridLayout_2.addWidget(self.applyButton_1, 7, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.resetButton.setFont(font)
        self.resetButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton.setObjectName("resetButton")
        self.gridLayout_2.addWidget(self.resetButton, 7, 1, 1, 1)
        self.applyButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.applyButton_2.setFont(font)
        self.applyButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.applyButton_2.setObjectName("applyButton_2")
        self.gridLayout_2.addWidget(self.applyButton_2, 7, 2, 1, 1)
        self.resetButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.resetButton_2.setFont(font)
        self.resetButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetButton_2.setObjectName("resetButton_2")
        self.gridLayout_2.addWidget(self.resetButton_2, 7, 3, 1, 1)
        self.applyAllButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.applyAllButton.setFont(font)
        self.applyAllButton.setObjectName("applyAllButton")
        self.gridLayout_2.addWidget(self.applyAllButton, 8, 2, 1, 1)
        self.resetAllButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.resetAllButton.setFont(font)
        self.resetAllButton.setObjectName("resetAllButton")
        self.gridLayout_2.addWidget(self.resetAllButton, 8, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Chosen files:"))
        self.pushButton.setText(_translate("MainWindow", "Choose files"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.label_4.setText(_translate("MainWindow", "File: (modification time, creation time):"))
        self.label_2.setText(_translate("MainWindow", "Change modification time:"))
        self.label_3.setText(_translate("MainWindow", "Change creation time:"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "MMM dd yyyy HH:mm:ss"))
        self.dateTimeEdit_2.setDisplayFormat(_translate("MainWindow", "MMM dd yyyy HH:mm:ss"))
        self.applyButton_1.setText(_translate("MainWindow", "Apply"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.applyButton_2.setText(_translate("MainWindow", "Apply"))
        self.resetButton_2.setText(_translate("MainWindow", "Reset"))
        self.applyAllButton.setText(_translate("MainWindow", "Apply all"))
        self.resetAllButton.setText(_translate("MainWindow", "Reset all"))
